### ISSUE TITLE
Fix export to CSV

### ISSUE THREAD

**Issue by critzo** [m-lab/measure-app#37]
- #27 Export to CSV includes only 10 tests
- #26 Export to CSV doesn't work in Debian (verify if still true)
- #21 Field: $$hashkey appears in CSV file and impacts headers vs values in CSV

**Comment by georgiamoon** [comment]
This is a bucket bug for #27, #26, #21,

**Comment by critzo** [comment]
All items have been resolved and tested.

**Comment by georgiamoon** [comment]
Is it working for you? I'm having an issue, but I'm also assuming that it's
because I'm on Amtrak.

@sajacy -- if you have a moment to test since you aren't on Amtrak atm,
that'd be stellar..

On Thu, Oct 29, 2015 at 11:53 AM, critzo notifications@github.com wrote:

> Closed #37 https://github.com/m-lab/measure-app/issues/37.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/m-lab/measure-app/issues/37#event-449383395.

## 

Georgia Bullen
Open Technology Institute http://newamerica.org/oti/ @ New America
http://newamerica.org
@georgiamoon http://twitter.com/georgiamoon

*Note: *Our address is changing on November 2nd:
740 15th Street NW, Suite 900, Washington DC, 20005

**Comment by critzo** [comment]
Re-opened to confirm. I checked this morning prior to leaving home- export worked when I used the CRX version, but not when running the unpacked extension. Just confirmed on Amtrak, unpacked extension does not export. About to test CRX again, but need to run test on Amtrak wifi first.

**Comment by critzo** [comment]
Just confirmed that export to csv indeed is not working currently. Jeff, could you investigate?

**Comment by georgiamoon** [comment]
I'm not 100% how to fix, but I think it's just an array count issue. I
might be wrong @sajacy

On Thu, Oct 29, 2015 at 12:16 PM, critzo notifications@github.com wrote:

> Just confirmed that export to csv indeed is not working currently. Jeff,
> could you investigate?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/m-lab/measure-app/issues/37#issuecomment-152232257.

## 

Georgia Bullen
Open Technology Institute http://newamerica.org/oti/ @ New America
http://newamerica.org
@georgiamoon http://twitter.com/georgiamoon

*Note: *Our address is changing on November 2nd:
740 15th Street NW, Suite 900, Washington DC, 20005

**Comment by sajacy** [comment]
I'll investigate now.

**Comment by critzo** [comment]
Confirmed!
